# Generated by Django 4.2.16 on 2025-08-10 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("products", "Товары"),
                            ("orders", "Заказы"),
                            ("stocks", "Остатки"),
                        ],
                        max_length=50,
                        verbose_name="Тип синхронизации",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Начата"),
                            ("completed", "Завершена"),
                            ("failed", "Ошибка"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "records_processed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Обработано записей"
                    ),
                ),
                (
                    "errors_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество ошибок"
                    ),
                ),
                (
                    "error_details",
                    models.JSONField(
                        default=list,
                        help_text="Список ошибок, возникших при синхронизации",
                        verbose_name="Детали ошибок",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время начала"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время завершения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог синхронизации",
                "verbose_name_plural": "Логи синхронизации",
                "db_table": "sync_logs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["sync_type", "status"],
                        name="sync_logs_sync_ty_e75e61_idx",
                    ),
                    models.Index(
                        fields=["started_at"], name="sync_logs_started_2c7a3f_idx"
                    ),
                    models.Index(
                        fields=["status", "started_at"],
                        name="sync_logs_status_39138b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Тип выполненного действия (create, update, delete, login, etc.)",
                        max_length=100,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="Тип объекта над которым выполнено действие (User, Product, Order, etc.)",
                        max_length=50,
                        verbose_name="Тип ресурса",
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        help_text="Идентификатор объекта",
                        max_length=100,
                        verbose_name="ID ресурса",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        default=dict,
                        help_text="JSON с деталями изменений",
                        verbose_name="Изменения",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP адрес пользователя", verbose_name="IP адрес"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        help_text="Браузер и устройство пользователя",
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время действия"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись аудита",
                "verbose_name_plural": "Аудиторский журнал",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_logs_user_id_88267f_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_logs_resourc_bda8a6_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="audit_logs_action_474804_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_logs_timesta_423be6_idx"
                    ),
                ],
            },
        ),
    ]
