# Generated by Django 4.2.16 on 2025-08-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synclog",
            name="sync_type",
            field=models.CharField(
                choices=[
                    ("products", "Товары"),
                    ("stocks", "Остатки"),
                    ("orders", "Заказы"),
                    ("prices", "Цены"),
                ],
                max_length=50,
                verbose_name="Тип синхронизации",
            ),
        ),
    ]
