# Generated by Django 4.2.16 on 2025-08-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_synclog_sync_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synclog",
            name="error_details",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список ошибок, возникших при синхронизации",
                verbose_name="Детали ошибок",
            ),
        ),
    ]
