# Generated by Django 5.2.7 on 2025-10-26 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_alter_synclog_error_details"),
        (
            "products",
            "0012_rename_import_sess_import__2f8c7d_idx_import_sess_import__f1fb4c_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("onec_id", models.CharField(max_length=100, verbose_name="ID в 1С")),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("created", "Создан"),
                            ("updated", "Обновлен"),
                            ("skipped", "Пропущен"),
                            ("error", "Ошибка"),
                        ],
                        max_length=20,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Успешно"),
                            ("failed", "Ошибка"),
                            ("warning", "Предупреждение"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Дополнительная информация: старые/новые значения, причина пропуска",
                        verbose_name="Детали операции",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_logs",
                        to="products.importsession",
                        verbose_name="Сессия импорта",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог синхронизации клиента",
                "verbose_name_plural": "Логи синхронизации клиентов",
                "db_table": "customer_sync_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "operation_type"],
                        name="customer_sy_session_540055_idx",
                    ),
                    models.Index(
                        fields=["onec_id"], name="customer_sy_onec_id_23fd73_idx"
                    ),
                    models.Index(
                        fields=["status"], name="customer_sy_status_a7c9af_idx"
                    ),
                ],
            },
        ),
    ]
