# Generated by Django 5.2.7 on 2025-10-29 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_update_customer_sync_log_for_conflicts"),
        (
            "products",
            "0012_rename_import_sess_import__2f8c7d_idx_import_sess_import__f1fb4c_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customersynclog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Лог синхронизации клиентов",
                "verbose_name_plural": "Логи синхронизации клиентов",
            },
        ),
        migrations.RemoveIndex(
            model_name="customersynclog",
            name="customer_sy_session_540055_idx",
        ),
        migrations.RemoveIndex(
            model_name="customersynclog",
            name="customer_sy_onec_id_23fd73_idx",
        ),
        migrations.RemoveIndex(
            model_name="customersynclog",
            name="customer_sy_status_a7c9af_idx",
        ),
        migrations.RenameIndex(
            model_name="syncconflict",
            new_name="sync_confli_custome_b810ba_idx",
            old_name="sync_confli_custome_idx",
        ),
        migrations.RenameIndex(
            model_name="syncconflict",
            new_name="sync_confli_is_reso_8c4a0e_idx",
            old_name="sync_confli_is_reso_idx",
        ),
        migrations.RenameIndex(
            model_name="syncconflict",
            new_name="sync_confli_conflic_93c33e_idx",
            old_name="sync_confli_conflic_idx",
        ),
        migrations.AddField(
            model_name="customersynclog",
            name="correlation_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID для отслеживания связанных операций",
                max_length=50,
                verbose_name="Correlation ID",
            ),
        ),
        migrations.AddField(
            model_name="customersynclog",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клиент",
            ),
        ),
        migrations.AddField(
            model_name="customersynclog",
            name="customer_email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, verbose_name="Email клиента"
            ),
        ),
        migrations.AddField(
            model_name="customersynclog",
            name="duration_ms",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Длительность операции в миллисекундах",
                null=True,
                verbose_name="Длительность (мс)",
            ),
        ),
        migrations.AddField(
            model_name="customersynclog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Дата операции"
            ),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="details",
            field=models.JSONField(
                default=dict,
                help_text="Структурированные данные операции",
                verbose_name="Детали операции",
            ),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="onec_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, verbose_name="ID в 1С"
            ),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("import_from_1c", "Импорт из 1С"),
                    ("export_to_1c", "Экспорт в 1С"),
                    ("sync_changes", "Синхронизация изменений"),
                    ("customer_identification", "Идентификация клиента"),
                    ("conflict_resolution", "Разрешение конфликтов"),
                    ("data_validation", "Валидация данных"),
                    ("batch_operation", "Пакетная операция"),
                    ("created", "Создан"),
                    ("updated", "Обновлен"),
                    ("skipped", "Пропущен"),
                    ("error", "Ошибка"),
                    ("identify_customer", "Идентификация клиента"),
                    ("notification_failed", "Ошибка отправки уведомления"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Тип операции",
            ),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Сессия импорта (опционально)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_logs",
                to="products.importsession",
                verbose_name="Сессия импорта",
            ),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Успешно"),
                    ("error", "Ошибка"),
                    ("warning", "Предупреждение"),
                    ("skipped", "Пропущено"),
                    ("pending", "В процессе"),
                    ("failed", "Ошибка"),
                    ("not_found", "Не найден"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy поле, используйте customer вместо этого",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_sync_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь (legacy)",
            ),
        ),
        migrations.AddIndex(
            model_name="customersynclog",
            index=models.Index(
                fields=["operation_type", "status", "created_at"],
                name="customer_sy_operati_e04946_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customersynclog",
            index=models.Index(
                fields=["customer_email"], name="customer_sy_custome_a9530d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customersynclog",
            index=models.Index(
                fields=["correlation_id"], name="customer_sy_correla_9e3b69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customersynclog",
            index=models.Index(
                fields=["created_at"], name="customer_sy_created_477fe0_idx"
            ),
        ),
    ]
