"""Миграция: добавление моделей новостей и подписок на рассылку."""

# Generated by Django 5.2.7 on 2025-11-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    """Описывает создание News и Newsletter моделей."""

    dependencies = [
        ("common", "0008_alter_customersynclog_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Заголовок новости",
                        max_length=200,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный идентификатор для URL",
                        max_length=255,
                        unique=True,
                        verbose_name="URL slug",
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text=(
                            "Краткое описание для главной страницы " "(до 500 символов)"
                        ),
                        max_length=500,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Полный текст новости (опционально)",
                        verbose_name="Полный текст",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение новости (опционально)",
                        null=True,
                        upload_to="news/%Y/%m/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="Имя автора (опционально)",
                        max_length=100,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Категория новости (акция, новинка, событие)",
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text=(
                            "Флаг публикации (только опубликованные " "видны на сайте)"
                        ),
                        verbose_name="Опубликована",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Дата и время публикации",
                        verbose_name="Дата публикации",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "db_table": "news",
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "published_at"],
                        name="news_is_publ_687a5d_idx",
                    ),
                    models.Index(fields=["slug"], name="news_slug_fb3ac9_idx"),
                    models.Index(
                        fields=["category", "published_at"],
                        name="news_categor_db4f5a_idx",
                    ),
                    models.Index(
                        fields=["published_at"], name="news_publish_b01c8c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Уникальный email адрес подписчика",
                        max_length=255,
                        unique=True,
                        verbose_name="Email адрес",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Флаг активности подписки (для отписки)",
                        verbose_name="Активна",
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Дата и время подписки",
                        verbose_name="Дата подписки",
                    ),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата и время отписки (null если активна)",
                        null=True,
                        verbose_name="Дата отписки",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP адрес при подписке (для антиспам)",
                        null=True,
                        verbose_name="IP адрес",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Браузер и устройство при подписке",
                        verbose_name="User Agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка на рассылку",
                "verbose_name_plural": "Подписки на рассылку",
                "db_table": "newsletter_subscriptions",
                "ordering": ["-subscribed_at"],
                "indexes": [
                    models.Index(fields=["email"], name="newsletter__email_71b1f8_idx"),
                    models.Index(
                        fields=["is_active", "subscribed_at"],
                        name="newsletter__is_acti_a85614_idx",
                    ),
                    models.Index(
                        fields=["subscribed_at"], name="newsletter__subscri_497fe4_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(is_active=True, unsubscribed_at__isnull=True)
                            | models.Q(is_active=False, unsubscribed_at__isnull=False)
                        ),
                        name="newsletter_active_consistency",
                    )
                ],
            },
        ),
    ]
