# Generated by Django 5.2.7 on 2025-11-29 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def migrate_news_categories(apps, schema_editor):
    News = apps.get_model("common", "News")

    for news in News.objects.all():
        val = news.category
        if not val:
            continue

        # If it's not a digit, clear the field (set to None)
        if not val.isdigit():
            news.category = None
            news.save()


def reverse_migrate_news_categories(apps, schema_editor):
    News = apps.get_model("common", "News")
    Category = apps.get_model("common", "Category")

    for news in News.objects.all():
        if news.category and news.category.isdigit():
            try:
                category = Category.objects.get(id=int(news.category))
                news.category = category.name
                news.save()
            except Category.DoesNotExist:
                pass


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0009_add_newsletter_and_news_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Название категории (уникальное)",
                        max_length=100,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-дружественный идентификатор (генерируется из названия)",
                        max_length=100,
                        unique=True,
                        verbose_name="URL-идентификатор",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="SEO-описание категории для мета-тегов",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "meta_keywords",
                    models.TextField(
                        blank=True,
                        help_text="SEO-ключевые слова через запятую",
                        verbose_name="Meta-ключевые слова",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="SEO-описание для поисковых систем",
                        verbose_name="Meta-описание",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Флаг активности категории",
                        verbose_name="Активна",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания категории",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего обновления категории",
                        verbose_name="Дата обновления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["parent", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Аудит лог",
                "verbose_name_plural": "Аудит логи",
            },
        ),
        migrations.AlterModelOptions(
            name="customersynclog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Лог синхронизации клиента",
                "verbose_name_plural": "Логи синхронизации клиентов",
            },
        ),
        migrations.RemoveConstraint(
            model_name="newsletter",
            name="newsletter_active_consistency",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_user_id_88267f_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_resourc_bda8a6_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_action_474804_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_timesta_423be6_idx",
        ),
        migrations.RemoveIndex(
            model_name="customersynclog",
            name="customer_sy_operati_e04946_idx",
        ),
        migrations.RemoveIndex(
            model_name="customersynclog",
            name="customer_sy_custome_a9530d_idx",
        ),
        migrations.RemoveIndex(
            model_name="customersynclog",
            name="customer_sy_correla_9e3b69_idx",
        ),
        migrations.RemoveIndex(
            model_name="customersynclog",
            name="customer_sy_created_477fe0_idx",
        ),
        migrations.RemoveIndex(
            model_name="news",
            name="news_slug_fb3ac9_idx",
        ),
        migrations.RemoveIndex(
            model_name="news",
            name="news_publish_b01c8c_idx",
        ),
        migrations.RemoveIndex(
            model_name="newsletter",
            name="newsletter__email_71b1f8_idx",
        ),
        migrations.RemoveIndex(
            model_name="newsletter",
            name="newsletter__subscri_497fe4_idx",
        ),
        migrations.RemoveIndex(
            model_name="syncconflict",
            name="sync_confli_custome_b810ba_idx",
        ),
        migrations.RemoveIndex(
            model_name="syncconflict",
            name="sync_confli_is_reso_8c4a0e_idx",
        ),
        migrations.RemoveIndex(
            model_name="syncconflict",
            name="sync_confli_conflic_93c33e_idx",
        ),
        migrations.RemoveIndex(
            model_name="synclog",
            name="sync_logs_sync_ty_e75e61_idx",
        ),
        migrations.RemoveIndex(
            model_name="synclog",
            name="sync_logs_started_2c7a3f_idx",
        ),
        migrations.RemoveIndex(
            model_name="synclog",
            name="sync_logs_status_39138b_idx",
        ),
        migrations.RenameIndex(
            model_name="news",
            new_name="common_news_is_publ_3ac01b_idx",
            old_name="news_is_publ_687a5d_idx",
        ),
        migrations.RenameIndex(
            model_name="news",
            new_name="common_news_categor_a2673c_idx",
            old_name="news_categor_db4f5a_idx",
        ),
        migrations.RenameIndex(
            model_name="newsletter",
            new_name="common_news_is_acti_7549a0_idx",
            old_name="newsletter__is_acti_a85614_idx",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="changes",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="customersynclog",
            name="customer_email",
        ),
        migrations.RemoveField(
            model_name="customersynclog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="syncconflict",
            name="conflicting_fields",
        ),
        migrations.RemoveField(
            model_name="syncconflict",
            name="onec_data",
        ),
        migrations.RemoveField(
            model_name="syncconflict",
            name="platform_data",
        ),
        migrations.RemoveField(
            model_name="syncconflict",
            name="resolution_details",
        ),
        migrations.RemoveField(
            model_name="syncconflict",
            name="resolved_by",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Дата и время создания записи",
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auditlog",
            name="details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Детальная информация об действии в формате JSON",
                verbose_name="Детали",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего обновления записи",
                verbose_name="Дата обновления",
            ),
        ),
        migrations.AddField(
            model_name="customersynclog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP адрес клиента",
                null=True,
                verbose_name="IP адрес",
            ),
        ),
        migrations.AddField(
            model_name="customersynclog",
            name="user_agent",
            field=models.TextField(
                blank=True,
                help_text="User Agent строка браузера",
                verbose_name="User Agent",
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, если подписка создана через аутентификацию",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="syncconflict",
            name="details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Детальная информация о конфликте в формате JSON",
                verbose_name="Детали",
            ),
        ),
        migrations.AddField(
            model_name="syncconflict",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего обновления записи",
                verbose_name="Дата обновления",
            ),
        ),
        migrations.AddField(
            model_name="synclog",
            name="correlation_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Уникальный идентификатор для группы связанных операций",
                null=True,
                unique=True,
                verbose_name="ID корреляции",
            ),
        ),
        migrations.AddField(
            model_name="synclog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Дата и время создания записи",
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="synclog",
            name="duration_ms",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Время выполнения в миллисекундах",
                null=True,
                verbose_name="Длительность (мс)",
            ),
        ),
        migrations.AddField(
            model_name="synclog",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего обновления записи",
                verbose_name="Дата обновления",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                db_index=True,
                help_text="Тип действия (создание, обновление, удаление)",
                max_length=50,
                verbose_name="Действие",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP адрес пользователя",
                null=True,
                verbose_name="IP адрес",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="resource_id",
            field=models.CharField(
                db_index=True,
                help_text="Идентификатор измененного ресурса",
                max_length=50,
                verbose_name="ID ресурса",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="resource_type",
            field=models.CharField(
                db_index=True,
                help_text="Тип измененного ресурса",
                max_length=50,
                verbose_name="Тип ресурса",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь, выполнивший действие",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(
                blank=True,
                help_text="User Agent строка браузера",
                verbose_name="User Agent",
            ),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="correlation_id",
            field=models.UUIDField(
                db_index=True,
                help_text="ID для группировки связанных операций",
                verbose_name="ID корреляции",
            ),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время создания записи",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="customer",
            field=models.ForeignKey(
                help_text="Связанный пользователь",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Детальная информация об операции в формате JSON",
                verbose_name="Детали",
            ),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="duration_ms",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Время выполнения в миллисекундах",
                null=True,
                verbose_name="Длительность (мс)",
            ),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="error_message",
            field=models.TextField(
                blank=True,
                help_text="Текстовое описание ошибки",
                verbose_name="Сообщение об ошибке",
            ),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="onec_id",
            field=models.CharField(
                db_index=True,
                help_text="Идентификатор клиента в системе 1С",
                max_length=36,
                verbose_name="ID в 1С",
            ),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="operation_type",
            field=models.CharField(
                db_index=True,
                help_text="Тип операции с клиентом",
                max_length=50,
                verbose_name="Тип операции",
            ),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="session",
            field=models.CharField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Идентификатор сессии пользователя",
                max_length=255,
                verbose_name="Сессия",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="status",
            field=models.CharField(
                db_index=True,
                help_text="Статус операции",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего обновления записи",
                verbose_name="Дата обновления",
            ),
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS news_category_4f2b8f_idx; DROP INDEX IF EXISTS news_categor_db4f5a_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="news",
            name="category",
            field=models.CharField(
                blank=True,
                db_index=False,
                help_text="Категория новости (акция, новинка, событие)",
                max_length=50,
                null=True,
                verbose_name="Категория",
            ),
        ),
        migrations.RunSQL(
            sql=r"UPDATE news SET category = NULL;", reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(
                help_text="Полное содержимое новости (HTML или Markdown)",
                verbose_name="Содержание",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время создания записи",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="excerpt",
            field=models.TextField(
                blank=True,
                help_text="Краткое описание новости для превью (до 200 символов)",
                verbose_name="Краткое описание",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Изображение для новости (опционально)",
                null=True,
                upload_to="news/images/%Y/%m/%d/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="is_published",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Флаг публикации новости",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата и время публикации новости",
                null=True,
                verbose_name="Дата публикации",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(
                help_text="Уникальный идентификатор для URL (генерируется из заголовка)",
                max_length=200,
                unique=True,
                verbose_name="URL-идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Заголовок новости (отображается в списке и заголовке страницы)",
                max_length=200,
                verbose_name="Заголовок",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время последнего обновления записи",
                verbose_name="Дата обновления",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="Email адрес для подписки",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP адрес при подписке/отписке",
                null=True,
                verbose_name="IP адрес",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Флаг активности подписки",
                verbose_name="Активна",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="subscribed_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время подписки",
                verbose_name="Дата подписки",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="unsubscribed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата и время отписки от рассылки",
                null=True,
                verbose_name="Дата отписки",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="user_agent",
            field=models.TextField(
                blank=True,
                help_text="User Agent строка браузера",
                verbose_name="User Agent",
            ),
        ),
        migrations.AlterField(
            model_name="syncconflict",
            name="conflict_type",
            field=models.CharField(
                db_index=True,
                help_text="Тип обнаруженного конфликта данных",
                max_length=50,
                verbose_name="Тип конфликта",
            ),
        ),
        migrations.AlterField(
            model_name="syncconflict",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время создания записи",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="syncconflict",
            name="customer",
            field=models.ForeignKey(
                help_text="Клиент, с которым связан конфликт",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="syncconflict",
            name="is_resolved",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Флаг разрешения конфликта",
                verbose_name="Разрешен",
            ),
        ),
        migrations.AlterField(
            model_name="syncconflict",
            name="resolution_strategy",
            field=models.CharField(
                db_index=True,
                help_text="Выбранная стратегия разрешения конфликта",
                max_length=50,
                verbose_name="Стратегия разрешения",
            ),
        ),
        migrations.AlterField(
            model_name="synclog",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Время завершения операции (успешно)",
                null=True,
                verbose_name="Завершение",
            ),
        ),
        migrations.AlterField(
            model_name="synclog",
            name="error_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Детальная информация об ошибках в формате JSON",
                verbose_name="Детали ошибок",
            ),
        ),
        migrations.AlterField(
            model_name="synclog",
            name="errors_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Количество обнаруженных ошибок",
                verbose_name="Количество ошибок",
            ),
        ),
        migrations.AlterField(
            model_name="synclog",
            name="records_processed",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Количество обработанных записей",
                verbose_name="Обработано записей",
            ),
        ),
        migrations.AlterField(
            model_name="synclog",
            name="started_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Время начала операции",
                verbose_name="Начало",
            ),
        ),
        migrations.AlterField(
            model_name="synclog",
            name="status",
            field=models.CharField(
                db_index=True,
                help_text="Текущий статус операции",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="synclog",
            name="sync_type",
            field=models.CharField(
                db_index=True,
                help_text="Тип операции синхронизации (импорт, экспорт и т.д.)",
                max_length=50,
                verbose_name="Тип синхронизации",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "action", "created_at"],
                name="common_audi_user_id_422d78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["resource_type", "resource_id", "created_at"],
                name="common_audi_resourc_c6f91b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customersynclog",
            index=models.Index(
                fields=["correlation_id", "created_at"],
                name="common_cust_correla_5663a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customersynclog",
            index=models.Index(
                fields=["customer", "operation_type", "created_at"],
                name="common_cust_custome_f87799_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="newsletter",
            index=models.Index(
                fields=["email", "is_active"], name="common_news_email_41d8d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncconflict",
            index=models.Index(
                fields=["customer", "conflict_type", "created_at"],
                name="common_sync_custome_31b2f5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="syncconflict",
            index=models.Index(
                fields=["is_resolved", "resolved_at"],
                name="common_sync_is_reso_ef6f5b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["correlation_id", "started_at"],
                name="common_sync_correla_a0cdf5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["sync_type", "status", "started_at"],
                name="common_sync_sync_ty_ce11e1_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="auditlog",
            table=None,
        ),
        migrations.AlterModelTable(
            name="customersynclog",
            table=None,
        ),
        migrations.AlterModelTable(
            name="news",
            table=None,
        ),
        migrations.AlterModelTable(
            name="newsletter",
            table=None,
        ),
        migrations.AlterModelTable(
            name="syncconflict",
            table=None,
        ),
        migrations.AlterModelTable(
            name="synclog",
            table=None,
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Родительская категория для иерархии",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.category",
                verbose_name="Родительская категория",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Категория новости (выбор из существующих)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="common.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent", "name"], name="common_cate_parent__eb4d0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active", "name"], name="common_cate_is_acti_71870d_idx"
            ),
        ),
    ]
