# Generated by Django 5.2.7 on 2025-12-04 03:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0010_category_alter_auditlog_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
