# Generated by Django 5.2.7 on 2025-12-27 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0011_alter_category_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="Заголовок статьи (отображается в списке и заголовке страницы)",
                        max_length=200,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный идентификатор для URL (генерируется из заголовка)",
                        max_length=200,
                        unique=True,
                        verbose_name="URL-идентификатор",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Подзаголовок статьи (опционально)",
                        max_length=200,
                        verbose_name="Подзаголовок",
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Краткое описание статьи для превью (до 200 символов)",
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Полное содержимое статьи (HTML или Markdown)",
                        verbose_name="Содержание",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение для статьи (опционально)",
                        null=True,
                        upload_to="blog/images/%Y/%m/%d/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="Имя автора (опционально)",
                        max_length=100,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Флаг публикации статьи",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата и время публикации статьи",
                        null=True,
                        verbose_name="Дата публикации",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO заголовок для поисковых систем (опционально)",
                        max_length=200,
                        verbose_name="SEO заголовок",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="SEO описание для поисковых систем (опционально)",
                        verbose_name="SEO описание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего обновления записи",
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Категория статьи (выбор из существующих)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to="common.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья блога",
                "verbose_name_plural": "Статьи блога",
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "published_at"],
                        name="common_blog_is_publ_bc48df_idx",
                    ),
                    models.Index(
                        fields=["category", "published_at"],
                        name="common_blog_categor_e2e841_idx",
                    ),
                ],
            },
        ),
    ]
