# Generated by Django 5.2.7 on 2026-01-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0012_blogpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время создания записи",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего обновления записи",
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email адрес получателя уведомлений",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Имя получателя для персонализации писем",
                        max_length=100,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Флаг активности получателя",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "notify_new_orders",
                    models.BooleanField(
                        default=False,
                        help_text="Уведомления о новых заказах",
                        verbose_name="Новые заказы",
                    ),
                ),
                (
                    "notify_order_cancelled",
                    models.BooleanField(
                        default=False,
                        help_text="Уведомления об отмене заказов",
                        verbose_name="Отмена заказов",
                    ),
                ),
                (
                    "notify_user_verification",
                    models.BooleanField(
                        default=False,
                        help_text="Уведомления о новых заявках на верификацию B2B партнёров",
                        verbose_name="Верификация B2B",
                    ),
                ),
                (
                    "notify_pending_queue",
                    models.BooleanField(
                        default=False,
                        help_text="Уведомления о превышении очереди pending верификаций",
                        verbose_name="Alert очереди",
                    ),
                ),
                (
                    "notify_low_stock",
                    models.BooleanField(
                        default=False,
                        help_text="Уведомления о малом остатке товаров",
                        verbose_name="Малый остаток",
                    ),
                ),
                (
                    "notify_daily_summary",
                    models.BooleanField(
                        default=False,
                        help_text="Ежедневные сводные отчёты",
                        verbose_name="Ежедневный отчёт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель уведомлений",
                "verbose_name_plural": "Получатели уведомлений",
                "ordering": ["email"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "notify_new_orders"],
                        name="common_noti_is_acti_7142fa_idx",
                    ),
                    models.Index(
                        fields=["is_active", "notify_user_verification"],
                        name="common_noti_is_acti_245db3_idx",
                    ),
                ],
            },
        ),
    ]
