# Generated by Django 5.2.7 on 2026-01-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0013_notification_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customersynclog",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("updated", "Обновлен"),
                    ("skipped", "Пропущен"),
                    ("error", "Ошибка"),
                    ("import_from_1c", "Импорт из 1С"),
                    ("export_to_1c", "Экспорт в 1С"),
                    ("customer_identification", "Идентификация клиента"),
                    ("conflict_resolution", "Разрешение конфликта"),
                    ("sync_changes", "Синхронизация изменений"),
                    ("batch_operation", "Пакетная операция"),
                    ("data_validation", "Валидация данных"),
                    ("notification_failed", "Ошибка уведомления"),
                ],
                db_index=True,
                help_text="Тип операции с клиентом",
                max_length=50,
                verbose_name="Тип операции",
            ),
        ),
        migrations.AlterField(
            model_name="customersynclog",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Успешно"),
                    ("failed", "Ошибка"),
                    ("error", "Ошибка"),
                    ("warning", "Предупреждение"),
                    ("skipped", "Пропущено"),
                    ("pending", "Ожидание"),
                ],
                db_index=True,
                help_text="Статус операции",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
