# Generated by Django 5.2.7 on 2026-05-09 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0014_alter_customersynclog_operation_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "session_key",
                    models.CharField(
                        blank=True, help_text="Для анонимных пользователей", max_length=40, verbose_name="Ключ сессии"
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("pdp_contract", "Согласие на обработку ПДн для исполнения договора"),
                            ("marketing_email", "Согласие на получение рекламных рассылок"),
                        ],
                        max_length=30,
                        verbose_name="Тип согласия",
                    ),
                ),
                ("given_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата согласия")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP адрес")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("policy_version", models.CharField(default="1.0", max_length=20, verbose_name="Версия политики")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Согласие пользователя",
                "verbose_name_plural": "Согласия пользователей",
                "ordering": ["-given_at"],
            },
        ),
    ]
