# Generated by Django 5.2.7 on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0015_userconsent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userconsent",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Для анонимных пользователей",
                max_length=40,
                verbose_name="Ключ сессии",
            ),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="consent_type",
            field=models.CharField(
                choices=[
                    ("pdp_contract", "Согласие на обработку ПДн для исполнения договора"),
                    ("marketing_email", "Согласие на получение рекламных рассылок"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Тип согласия",
            ),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="given_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                verbose_name="Дата согласия",
            ),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="user_agent",
            field=models.CharField(blank=True, max_length=512, verbose_name="User Agent"),
        ),
        migrations.AddConstraint(
            model_name="userconsent",
            constraint=models.CheckConstraint(
                condition=models.Q(("user__isnull", False)) | ~models.Q(("session_key", "")),
                name="userconsent_user_or_session_required",
            ),
        ),
    ]
