# Generated by Django 5.2.7 on 2025-12-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                help_text="Рекомендуемый размер: 1920×600px",
                upload_to="promos/%Y/%m/",
                verbose_name="Изображение",
            ),
        ),
    ]
