# Generated by Django 5.2.7 on 2026-02-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banners", "0002_alter_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="type",
            field=models.CharField(
                choices=[("hero", "Геройский (Hero)"), ("marketing", "Маркетинговый")],
                default="hero",
                help_text="Тип определяет место и способ отображения баннера",
                max_length=20,
                verbose_name="Тип баннера",
            ),
        ),
    ]
