# Generated by Django 5.2.7 on 2026-02-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banners", "0003_banner_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="cta_text",
            field=models.CharField(
                blank=True, help_text="Текст call-to-action кнопки", max_length=50, verbose_name="Текст кнопки"
            ),
        ),
    ]
