# Generated by Django 5.2.7 on 2026-02-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_alter_banner_cta_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 1920×600px', upload_to='promos/%Y/%m/', verbose_name='Изображение'),
        ),
    ]
