# Generated by Django 5.2.7 on 2026-03-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banners", "0005_alter_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="mobile_image",
            field=models.ImageField(
                blank=True,
                help_text="Изображение для мобильных устройств (21:9, рекомендуемый размер: 1260×540px). Если не загружено — используется основное.",
                upload_to="promos/%Y/%m/",
                verbose_name="Мобильное изображение",
            ),
        ),
    ]
