# Generated by Django 5.2.7 on 2025-12-05
"""
Миграция CartItem с Product на ProductVariant.

BREAKING CHANGE: Очищает все существующие корзины перед миграцией.
"""

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def clear_all_carts(apps, schema_editor):
    """Очистить все корзины перед миграцией (BREAKING CHANGE)"""
    CartItem = apps.get_model("cart", "CartItem")
    CartItem.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_cart_cart_must_have_user_or_session"),
        ("products", "0033_alter_attributevalue_normalized_value"),
    ]

    operations = [
        # Шаг 1: Очистить все корзины
        migrations.RunPython(
            clear_all_carts,
            reverse_code=migrations.RunPython.noop,
        ),
        # Шаг 2: Удалить constraint на product
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        # Шаг 3: Удалить поле product
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        # Шаг 4: Добавить поле variant
        migrations.AddField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productvariant",
                verbose_name="Вариант товара",
                help_text="SKU-вариант товара с конкретными характеристиками (цвет, размер)",
            ),
        ),
        # Шаг 5: Добавить поле price_snapshot
        migrations.AddField(
            model_name="cartitem",
            name="price_snapshot",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="Снимок цены",
                help_text="Цена варианта на момент добавления в корзину",
                default=0,
            ),
            preserve_default=False,
        ),
        # Шаг 6: Установить новый unique_together на variant
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "variant")},
        ),
    ]
