# Generated by Django 4.2.16 on 2025-08-10 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="address",
            unique_together=set(),
        ),
    ]
