# Generated by Django 4.2.16 on 2025-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("retail", "Розничный покупатель"),
                    ("wholesale_level1", "Оптовик уровень 1"),
                    ("wholesale_level2", "Оптовик уровень 2"),
                    ("wholesale_level3", "Оптовик уровень 3"),
                    ("trainer", "Тренер/Фитнес-клуб"),
                    ("federation_rep", "Представитель федерации"),
                    ("admin", "Администратор"),
                ],
                default="retail",
                max_length=20,
                verbose_name="Роль пользователя",
            ),
        ),
    ]
