# Generated by Django 4.2.16 on 2025-09-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_in_1c",
            field=models.BooleanField(
                default=False,
                help_text=("Указывает, что пользователь был создан в 1С"),
                verbose_name="Создан в 1С",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_sync_at",
            field=models.DateTimeField(
                blank=True,
                help_text=("Дата и время последней синхронизации с 1С"),
                null=True,
                verbose_name="Последняя синхронизация",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="needs_1c_export",
            field=models.BooleanField(
                default=False,
                help_text=("Требует экспорта данных в 1С"),
                verbose_name="Требует экспорта в 1С",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="onec_id",
            field=models.CharField(
                blank=True,
                help_text=("Уникальный идентификатор клиента в 1С"),
                max_length=100,
                null=True,
                unique=True,
                verbose_name="ID в 1С",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sync_error_message",
            field=models.TextField(
                blank=True,
                help_text="Сообщение об ошибке при синхронизации с 1С",
                verbose_name="Ошибка синхронизации",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает синхронизации"),
                    ("synced", "Синхронизирован"),
                    ("error", "Ошибка синхронизации"),
                    ("conflict", "Конфликт данных"),
                ],
                default="pending",
                help_text="Статус синхронизации с 1С",
                max_length=20,
                verbose_name="Статус синхронизации",
            ),
        ),
        # Добавляем индексы для оптимизации производительности (PostgreSQL)
        migrations.RunSQL(
            """
            CREATE INDEX idx_users_onec_id
            ON users (onec_id)
            WHERE onec_id IS NOT NULL;
            """.strip(),
            reverse_sql="DROP INDEX IF EXISTS idx_users_onec_id;",
        ),
        migrations.RunSQL(
            """
            CREATE INDEX idx_users_sync_status
            ON users (sync_status);
            """.strip(),
            reverse_sql="DROP INDEX IF EXISTS idx_users_sync_status;",
        ),
        migrations.RunSQL(
            """
            CREATE INDEX idx_users_last_sync_at
            ON users (last_sync_at)
            WHERE last_sync_at IS NOT NULL;
            """.strip(),
            reverse_sql="DROP INDEX IF EXISTS idx_users_last_sync_at;",
        ),
    ]
