# Generated by Django 5.2.7 on 2025-10-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_add_1c_integration_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, unique=True, verbose_name="Email адрес"
            ),
        ),
    ]
