# Generated by Django 5.2.7 on 2025-10-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_update_user_email_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Email адрес",
            ),
        ),
    ]
