# Generated by Django 5.2.7 on 2025-12-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_increase_phone_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="building_section",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Корпус/строение"
            ),
        ),
    ]
