# Generated by Django 5.2.7 on 2025-12-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_add_building_section_to_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="legal_address",
            field=models.TextField(blank=True, verbose_name="Юридический адрес"),
        ),
        migrations.AlterField(
            model_name="company",
            name="legal_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Юридическое название"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="tax_id",
            field=models.CharField(blank=True, max_length=12, verbose_name="ИНН"),
        ),
    ]
