# Generated by Django 5.2.7 on 2026-08-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_add_users_tax_id_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("retail", "Розничный покупатель"),
                    ("wholesale_level1", "Оптовик уровень 1"),
                    ("wholesale_level2", "Оптовик уровень 2"),
                    ("wholesale_level3", "Оптовик уровень 3"),
                    ("wholesale_level4", "Оптовик уровень 4"),
                    ("trainer", "Тренер/Фитнес-клуб"),
                    ("federation_rep", "Представитель федерации"),
                    ("admin", "Администратор"),
                    ("unregistered", "Не зарегистрирован на портале"),
                ],
                default="retail",
                max_length=20,
                verbose_name="Роль пользователя",
            ),
        ),
    ]
