# Generated by Django 5.2.7 on 2026-08-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_add_wholesale_level4_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onec_price_type_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Вид цен из соглашения об условиях продаж (реквизит ТипЦенId выгрузки контрагентов). Заполняется импортом 1С; роль портала по нему выдаётся отдельно. Пустое значение означает «соглашения нет» либо «GUID неоднозначен».",
                max_length=100,
                verbose_name="GUID вида цен в 1С",
            ),
        ),
    ]
