# Generated by Django 5.2.7 on 2026-09-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_add_user_onec_price_type_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                choices=[("Россия", "Россия"), ("Беларусь", "Беларусь"), ("Казахстан", "Казахстан")],
                default="Россия",
                help_text="Страна регистрации B2B-клиента (для маршрутизации на специалиста)",
                max_length=20,
                verbose_name="Страна",
            ),
        ),
    ]
