# Generated by Django 5.2.7 on 2026-07-25 08:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0016_customercodesequence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusProgramSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Выключение прекращает начисления; накопленные бонусы сохраняются",
                        verbose_name="Программа активна",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Процент от стоимости товаров в заказе (без доставки)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Процент начисления",
                    ),
                ),
                (
                    "accrual_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает обработки"),
                            ("confirmed", "Подтвержден"),
                            ("processing", "В обработке"),
                            ("shipped", "Отправлен"),
                            ("delivered", "Доставлен"),
                            ("cancelled", "Отменен"),
                            ("refunded", "Возвращен"),
                        ],
                        default="delivered",
                        help_text="Начисление происходит при переходе мастер-заказа в этот статус",
                        max_length=50,
                        verbose_name="Статус заказа для начисления",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Настройки бонусной программы",
                "verbose_name_plural": "Настройки бонусной программы",
                "db_table": "bonus_program_settings",
            },
        ),
        migrations.CreateModel(
            name="BonusTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("accrual", "Начисление"), ("payout", "Выплата"), ("writeoff", "Списание")],
                        max_length=20,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Начисление — положительная, выплата и списание — отрицательная",
                        max_digits=10,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "percent_applied",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Снимок процента на момент начисления",
                        max_digits=5,
                        null=True,
                        verbose_name="Применённый процент",
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Снимок стоимости товаров на момент начисления",
                        max_digits=10,
                        null=True,
                        verbose_name="База начисления",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Обязателен для выплат и списаний: основание операции",
                        verbose_name="Комментарий",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bonus_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто создал",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Заполняется только для начислений",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bonus_transactions",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бонусная операция",
                "verbose_name_plural": "Бонусные операции",
                "db_table": "bonus_transactions",
                "ordering": ["-created_at", "-id"],
                "indexes": [models.Index(fields=["user", "created_at"], name="idx_bonus_user_created")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("transaction_type", "accrual"), ("amount__gt", 0)),
                            models.Q(("transaction_type__in", ["payout", "writeoff"]), ("amount__lt", 0)),
                            _connector="OR",
                        ),
                        name="check_bonus_amount_sign",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("transaction_type", "accrual")),
                        fields=("order",),
                        name="uniq_bonus_accrual_per_order",
                    ),
                ],
            },
        ),
    ]
