# Generated by Django 5.2.7 on 2026-07-25 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bonuses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonusprogramsettings",
            name="program_start_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Бонусы начисляются только по заказам, созданным не раньше этой даты. Пустое значение отключает отсечку — начисление пойдёт и по старым заказам",
                null=True,
                verbose_name="Дата запуска программы",
            ),
        ),
    ]
