# Generated by Django 4.2.16 on 2025-09-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL slug"
                    ),
                ),
                ("content", models.TextField(verbose_name="Содержимое")),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="SEO заголовок"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        blank=True, max_length=160, verbose_name="SEO описание"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликовано"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Страница",
                "verbose_name_plural": "Страницы",
                "ordering": ["title"],
            },
        ),
    ]
