# Generated by Django 4.2.16 on 2025-08-10 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_remove_brand_brands_unique_active_name_and_more"),
        ("orders", "0003_remove_order_orders_total_amount_positive_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "product")},
        ),
    ]
