# Generated by Django 5.2.7 on 2025-12-15 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_add_tracking_number"),
        ("products", "0035_add_variants_import_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="orderitem",
            name="order_items_order_i_f97371_idx",
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                help_text="SKU-вариант товара (размер, цвет)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.productvariant",
                verbose_name="Вариант товара",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant_info",
            field=models.CharField(
                blank=True,
                help_text="Размер, цвет и др. характеристики варианта",
                max_length=200,
                verbose_name="Информация о варианте",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("pickup", "Самовывоз"),
                    ("courier", "Курьерская доставка"),
                    ("post", "Почтовая доставка"),
                    ("transport_company", "Транспортная компания"),
                ],
                max_length=50,
                verbose_name="Способ доставки",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "variant")},
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["order", "variant"], name="order_items_order_i_c139e6_idx"
            ),
        ),
    ]
