# Generated by Django 5.2.7 on 2026-01-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_add_variant_to_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("pickup", "Самовывоз"),
                    ("courier", "Курьерская доставка"),
                    ("post", "Почтовая доставка"),
                    ("transport_company", "Транспортная компания"),
                    ("transport_schedule", "Транспортная компания (по расписанию)"),
                ],
                max_length=50,
                verbose_name="Способ доставки",
            ),
        ),
    ]
