# Generated by Django 5.2.7 on 2026-01-30 16:36

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("orders", "0007_alter_order_delivery_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sent_to_1c",
            field=models.BooleanField(default=False, verbose_name="Отправлен в 1С"),
        ),
        migrations.AddField(
            model_name="order",
            name="sent_to_1c_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата отправки в 1С"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status_1c",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Статус из 1С"
            ),
        ),
        AddIndexConcurrently(
            model_name="order",
            index=models.Index(
                fields=["sent_to_1c", "created_at"], name="idx_order_sent_to_1c_created"
            ),
        ),
    ]
