# Generated by Django 5.2.7 on 2026-01-30 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "orders",
            "0008_order_sent_to_1c_order_sent_to_1c_at_order_status_1c_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="idx_order_sent_to_1c_created",
        ),
        migrations.AlterField(
            model_name="order",
            name="sent_to_1c_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время отправки в 1С"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status_1c",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Статус из 1С"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                condition=models.Q(("sent_to_1c", False)),
                fields=["sent_to_1c", "created_at"],
                name="idx_order_sent_to_1c_created",
            ),
        ),
    ]
