# Generated by Django 5.2.7 on 2026-02-01 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_order_1c_fields_review_fixes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="idx_order_sent_to_1c_created",
        ),
        migrations.AddField(
            model_name="order",
            name="export_skipped",
            field=models.BooleanField(
                default=False,
                help_text="Заказ не прошёл валидацию для экспорта в 1С (например, нет товаров)",
                verbose_name="Пропущен при экспорте",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                condition=models.Q(("export_skipped", False), ("sent_to_1c", False)),
                fields=["sent_to_1c", "created_at"],
                name="idx_order_sent_to_1c_created",
            ),
        ),
    ]
