# Generated by Django 5.2.7 on 2026-05-05 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0014_delete_test_orders"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="uniq_master_order_customer_year_seq",
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("customer_year_sequence__isnull", False),
                    ("is_master", True),
                    ("order_year__isnull", False),
                    models.Q(("customer_code_snapshot", ""), _negated=True),
                ),
                fields=("customer_code_snapshot", "order_year", "customer_year_sequence"),
                name="uniq_master_order_customer_year_seq",
            ),
        ),
    ]
