# Generated by Django 5.2.7 on 2026-07-11 10:56

import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)


def seed_customer_code_sequence(apps, schema_editor):
    """Сидирует счётчик текущим максимумом среди существующих customer_code.

    Не хардкодит 0 -- защита от коллизий, если в окружении уже есть
    вручную проставленные коды (dev/staging могут отличаться от прода).
    """
    User = apps.get_model("users", "User")
    CustomerCodeSequence = apps.get_model("orders", "CustomerCodeSequence")

    max_value = 0
    codes = (
        User.objects.exclude(customer_code__isnull=True)
        .exclude(customer_code="")
        .values_list("customer_code", flat=True)
    )
    for code in codes:
        try:
            max_value = max(max_value, int(code))
        except (TypeError, ValueError):
            logger.warning("Пропущен нечисловой customer_code при сидировании счётчика: %r", code)
            continue

    CustomerCodeSequence.objects.update_or_create(pk=1, defaults={"last_value": max_value})


def noop_reverse(apps, schema_editor):
    """Обратной миграции для сида не требуется -- модель удаляется целиком."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0015_remove_order_uniq_master_order_customer_year_seq_and_more"),
        ("users", "0015_add_customer_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerCodeSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_value", models.PositiveIntegerField(default=0, verbose_name="Последнее выданное значение")),
            ],
            options={
                "verbose_name": "Счетчик кодов клиентов",
                "verbose_name_plural": "Счетчики кодов клиентов",
                "db_table": "customer_code_sequences",
            },
        ),
        migrations.RunPython(seed_customer_code_sequence, noop_reverse),
    ]
