/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/register/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Регистрация нового пользователя
     * @description Создание нового аккаунта B2C или B2B пользователя.
     *     Для B2B требуется верификация компании.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UserRegistration'];
        };
      };
      responses: {
        /** @description Пользователь успешно зарегистрирован */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserRegistrationResponse'];
          };
        };
        /** @description Ошибка валидации данных */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Вход в систему
     * @description Аутентификация пользователя с получением JWT токенов.
     *     Поддерживает как B2C, так и B2B пользователей.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Login'];
        };
      };
      responses: {
        /** @description Успешная аутентификация */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LoginResponse'];
          };
        };
        /** @description Неверные учетные данные */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Обновление токена доступа
     * @description Получение нового access токена на основе действующего refresh токена.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @description Refresh token */
            refresh: string;
          };
        };
      };
      responses: {
        /** @description Новый access token */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Новый JWT access token */
              access?: string;
            };
          };
        };
        /** @description Недействительный refresh токен */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/profile/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить профиль текущего пользователя */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Профиль пользователя */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserProfile'];
          };
        };
        /** @description Не авторизован */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Обновить профиль пользователя */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UserProfileUpdate'];
        };
      };
      responses: {
        /** @description Профиль успешно обновлен */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserProfile'];
          };
        };
      };
    };
    trace?: never;
  };
  '/products/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Получить список товаров
     * @description Получение каталога товаров с поддержкой фильтрации, поиска и пагинации.
     *     Цены адаптируются под роль пользователя (B2C/B2B).
     */
    get: {
      parameters: {
        query?: {
          /** @description ID категории для фильтрации */
          category_id?: number;
          /** @description Поиск по названию, описанию, артикулу */
          search?: string;
          /** @description Фильтр по бренду */
          brand?: string;
          /** @description Минимальная цена */
          min_price?: number;
          /** @description Максимальная цена */
          max_price?: number;
          /** @description Только товары в наличии */
          in_stock?: boolean;
          /** @description Номер страницы */
          page?: number;
          /** @description Количество товаров на странице */
          page_size?: number;
          /** @description Сортировка результатов */
          ordering?: 'name' | '-name' | 'price' | '-price' | 'created_at' | '-created_at';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Список товаров */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProductList'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/products/{id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить детали товара */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID товара */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Детали товара */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProductDetail'];
          };
        };
        /** @description Товар не найден */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/categories/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Получить дерево категорий
     * @description Возвращает иерархическую структуру категорий товаров.
     *     Поддерживает неограниченную вложенность.
     */
    get: {
      parameters: {
        query?: {
          /** @description ID родительской категории (null для корневых) */
          parent_id?: number;
          /** @description Максимальный уровень вложенности */
          level?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Дерево категорий */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Category'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/categories/{id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить категорию по ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Детали категории */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CategoryDetail'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/cart/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить корзину пользователя */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Содержимое корзины */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Cart'];
          };
        };
        /** @description Не авторизован */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/cart/items/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Добавить товар в корзину */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CartItemCreate'];
        };
      };
      responses: {
        /** @description Товар добавлен в корзину */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CartItem'];
          };
        };
        /** @description Ошибка валидации */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/cart/items/{id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Удалить товар из корзины */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Товар удален из корзины */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    /** Обновить количество товара в корзине */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID элемента корзины */
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            quantity: number;
          };
        };
      };
      responses: {
        /** @description Количество обновлено */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CartItem'];
          };
        };
      };
    };
    trace?: never;
  };
  '/orders/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить список заказов пользователя */
    get: {
      parameters: {
        query?: {
          /** @description Фильтр по статусу заказа */
          status?: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
          page?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Список заказов */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['OrderList'];
          };
        };
      };
    };
    put?: never;
    /**
     * Создать новый заказ
     * @description Создание заказа из текущей корзины пользователя.
     *     После создания корзина очищается.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['OrderCreate'];
        };
      };
      responses: {
        /** @description Заказ успешно создан */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['OrderDetail'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/orders/{id}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить детали заказа */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Детали заказа */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['OrderDetail'];
          };
        };
        /** @description Доступ запрещен */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Заказ не найден */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pages/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Получить список статических страниц
     * @description Возвращает список всех опубликованных статических страниц.
     *     Результат кэшируется на 24 часа для лучшей производительности.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Список статических страниц */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Page'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pages/{slug}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Получить содержимое страницы
     * @description Возвращает полное содержимое статической страницы по URL slug.
     *     Включает HTML контент, SEO метаданные и кэширование.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /**
           * @description URL slug страницы
           * @example about-company
           */
          slug: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Содержимое страницы */
        200: {
          headers: {
            /** @description public, max-age=86400 */
            'Cache-Control'?: string;
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PageDetail'];
          };
        };
        /** @description Страница не найдена */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    UserRegistration: {
      /**
       * Format: email
       * @description Email пользователя
       */
      email: string;
      /** @description Пароль (минимум 8 символов) */
      password: string;
      /** @description Имя */
      first_name: string;
      /** @description Фамилия */
      last_name: string;
      /** @description Телефон в формате +7XXXXXXXXXX */
      phone?: string;
      /**
       * @description Роль пользователя
       * @enum {string}
       */
      role:
        | 'retail'
        | 'wholesale_level1'
        | 'wholesale_level2'
        | 'wholesale_level3'
        | 'trainer'
        | 'federation_rep'
        | 'admin';
      /** @description Название компании (для B2B) */
      company_name?: string;
      /** @description ИНН (для B2B) */
      tax_id?: string;
    };
    UserRegistrationResponse: {
      id?: number;
      /** Format: email */
      email?: string;
      first_name?: string;
      last_name?: string;
      role?: string;
      /** @description Подтвержден ли аккаунт */
      is_verified?: boolean;
      /** @description Требуется ли верификация (для B2B) */
      verification_required?: boolean;
    };
    Login: {
      /** Format: email */
      email: string;
      password: string;
    };
    LoginResponse: {
      /** @description JWT access token (срок действия 15 минут) */
      access?: string;
      /** @description JWT refresh token (срок действия 7 дней) */
      refresh?: string;
      user?: components['schemas']['UserProfile'];
    };
    UserProfile: {
      id?: number;
      /** Format: email */
      email?: string;
      first_name?: string;
      last_name?: string;
      phone?: string;
      /** @enum {string} */
      role?:
        | 'retail'
        | 'wholesale_level1'
        | 'wholesale_level2'
        | 'wholesale_level3'
        | 'trainer'
        | 'federation_rep'
        | 'admin';
      company_name?: string | null;
      tax_id?: string | null;
      is_verified?: boolean;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    UserProfileUpdate: {
      first_name?: string;
      last_name?: string;
      phone?: string;
      company_name?: string;
    };
    ProductList: {
      /** @description Общее количество товаров */
      count?: number;
      /** @description URL следующей страницы */
      next?: string | null;
      /** @description URL предыдущей страницы */
      previous?: string | null;
      results?: components['schemas']['Product'][];
    };
    Product: {
      id?: number;
      /** @description Название товара */
      name?: string;
      /** @description URL slug для SEO */
      slug?: string;
      /** @description Артикул товара */
      sku?: string;
      /** @description Краткое описание */
      description?: string;
      category?: components['schemas']['CategoryBreadcrumb'];
      /** @description Бренд товара */
      brand?: string;
      price?: components['schemas']['Price'];
      /** @description Количество на складе */
      stock_quantity?: number;
      /**
       * @description Минимальное количество для заказа
       * @default 1
       */
      min_order_quantity: number;
      images?: components['schemas']['ProductImage'][];
      /** Format: float */
      rating?: number | null;
      reviews_count?: number;
      /** @description Доступен ли товар для заказа */
      is_available?: boolean;
      /** Format: date-time */
      created_at?: string;
    };
    ProductDetail: components['schemas']['Product'] & {
      /** @description Полное описание товара */
      full_description?: string;
      /**
       * @description Технические характеристики товара в формате ключ-значение
       * @example {
       *       "Материал": "Полиэстер 100%",
       *       "Размеры": "S, M, L, XL",
       *       "Вес": "0.5 кг",
       *       "Цвет": "Синий, красный, черный"
       *     }
       */
      specifications?: {
        [key: string]: unknown;
      };
      /** @description Варианты товара (цвет, размер, цены, остатки) */
      variants?: components['schemas']['ProductVariant'][];
      /** @description Похожие товары */
      related_products?: components['schemas']['Product'][];
    };
    ProductImage: {
      id?: number;
      /**
       * Format: uri
       * @description URL изображения
       */
      image?: string;
      /** @description Альтернативный текст */
      alt_text?: string;
      /** @description Является ли основным изображением */
      is_primary?: boolean;
    };
    ProductVariant: {
      /** @description ID варианта товара */
      id: number;
      /**
       * @description Артикул SKU
       * @example NIKE-AM-RED-42
       */
      sku: string;
      /**
       * @description Название цвета
       * @example Красный
       */
      color_name?: string | null;
      /**
       * @description Размер
       * @example 42
       */
      size_value?: string | null;
      /**
       * Format: decimal
       * @description Цена для текущего пользователя (роле-ориентированная)
       * @example 5990.00
       */
      current_price: string;
      /**
       * @description Hex-код цвета (если доступен из ColorMapping)
       * @example #FF0000
       */
      color_hex?: string | null;
      /**
       * @description Количество на складе
       * @example 15
       */
      stock_quantity: number;
      /**
       * @description Доступен для заказа (computed property)
       * @example true
       */
      is_in_stock: boolean;
      /**
       * @description Доступное количество (с учетом резерва, computed property)
       * @example 15
       */
      available_quantity: number;
      /**
       * Format: uri
       * @description Основное изображение варианта
       * @example /media/products/variants/nike-am-red.jpg
       */
      main_image?: string | null;
      /**
       * @description Галерея изображений варианта
       * @example [
       *       "/media/products/variants/nike-am-red-side.jpg"
       *     ]
       */
      gallery_images?: string[];
    };
    Price: {
      /**
       * Format: decimal
       * @description Розничная цена
       */
      retail?: number;
      wholesale?: {
        /**
         * Format: decimal
         * @description Оптовая цена уровень 1
         */
        level1?: number;
        /**
         * Format: decimal
         * @description Оптовая цена уровень 2
         */
        level2?: number;
        /**
         * Format: decimal
         * @description Оптовая цена уровень 3
         */
        level3?: number;
      } | null;
      /** @default RUB */
      currency: string;
      /**
       * Format: decimal
       * @description Цена для текущего пользователя
       */
      current?: number;
      /** @description Процент скидки для текущего пользователя */
      discount_percent?: number | null;
    };
    Category: {
      id?: number;
      /** @description Название категории */
      name?: string;
      /** @description URL slug */
      slug?: string;
      description?: string | null;
      /** @description ID родительской категории */
      parent_id?: number | null;
      /** @description Уровень вложенности */
      level?: number;
      /** @description Иконка категории (emoji или код) */
      icon?: string | null;
      /** @description Количество товаров в категории */
      products_count?: number;
      /** @description Дочерние категории */
      children?: components['schemas']['Category'][];
    };
    CategoryDetail: components['schemas']['Category'] & {
      breadcrumbs?: components['schemas']['CategoryBreadcrumb'][];
    };
    CategoryBreadcrumb: {
      id?: number;
      name?: string;
      slug?: string;
    };
    Cart: {
      id?: number;
      user_id?: number;
      items?: components['schemas']['CartItem'][];
      /** @description Общее количество товаров */
      total_items?: number;
      /**
       * Format: decimal
       * @description Общая стоимость корзины
       */
      total_price?: number;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    CartItem: {
      id?: number;
      product?: components['schemas']['Product'];
      quantity?: number;
      /**
       * Format: decimal
       * @description Цена за единицу (на момент добавления)
       */
      unit_price?: number;
      /**
       * Format: decimal
       * @description Общая стоимость позиции
       */
      total_price?: number;
      /** Format: date-time */
      added_at?: string;
    };
    CartItemCreate: {
      product_id: number;
      quantity: number;
    };
    OrderList: {
      count?: number;
      next?: string | null;
      previous?: string | null;
      results?: components['schemas']['Order'][];
    };
    Order: {
      id?: number;
      /** @description Номер заказа */
      order_number?: string;
      /** @enum {string} */
      status?: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
      /** Format: decimal */
      total_amount?: number;
      items_count?: number;
      /** Format: date-time */
      created_at?: string;
      /** Format: date */
      estimated_delivery?: string | null;
    };
    OrderDetail: components['schemas']['Order'] & {
      items?: components['schemas']['OrderItem'][];
      shipping_address?: components['schemas']['Address'];
      legal_address?: components['schemas']['Address'];
      payment_method?: string;
      delivery_method?: string;
      notes?: string | null;
    };
    OrderItem: {
      id?: number;
      product?: components['schemas']['Product'];
      quantity?: number;
      /**
       * Format: decimal
       * @description Цена за единицу на момент заказа
       */
      unit_price?: number;
      /** Format: decimal */
      total_price?: number;
    };
    OrderCreate: {
      shipping_address: components['schemas']['AddressCreate'];
      legal_address?: components['schemas']['AddressCreate'];
      /** @enum {string} */
      payment_method: 'card' | 'cash' | 'bank_transfer';
      /** @enum {string} */
      delivery_method: 'courier' | 'pickup' | 'post';
      notes?: string;
    };
    Address: {
      id?: number;
      full_name?: string;
      phone?: string;
      city?: string;
      street?: string;
      building?: string;
      apartment?: string | null;
      postal_code?: string;
    };
    AddressCreate: {
      full_name: string;
      phone: string;
      city: string;
      street: string;
      building: string;
      apartment?: string;
      postal_code: string;
    };
    Error: {
      /** @description Описание ошибки */
      detail?: string;
      /** @description Ошибки валидации полей */
      field_errors?: {
        [key: string]: string[];
      };
      /** @description Код ошибки для программной обработки */
      error_code?: string;
    };
    Page: {
      /** @description Уникальный идентификатор страницы */
      id?: number;
      /** @description Заголовок страницы */
      title?: string;
      /**
       * @description URL slug для SEO-дружественных URL
       * @example about-company
       */
      slug?: string;
      /**
       * @description HTML содержимое страницы (очищенное и безопасное)
       * @example <h1>О компании</h1><p>Мы лидеры в сфере спортивных товаров...</p>
       */
      content?: string;
      /**
       * @description SEO заголовок для meta title
       * @example О компании FREESPORT - лидер спортивных товаров
       */
      seo_title?: string;
      /**
       * @description SEO описание для meta description
       * @example FREESPORT - ведущий поставщик спортивных товаров с 2010 года. Качественные товары для всех видов спорта.
       */
      seo_description?: string;
      /**
       * Format: date-time
       * @description Время последнего обновления
       */
      updated_at?: string;
      /**
       * Format: date-time
       * @description Время создания страницы
       */
      created_at?: string;
    };
    PageDetail: components['schemas']['Page'] & {
      /**
       * @description Полное HTML содержимое страницы с санитизацией
       * @example <h1>О компании FREESPORT</h1>
       *     <p>Мы работаем на рынке спортивных товаров с 2010 года...</p>
       *     <ul>
       *       <li>Широкий ассортимент</li>
       *       <li>Гарантия качества</li>
       *       <li>Быстрая доставка</li>
       *     </ul>
       */
      content?: string;
    };
    PaginatedResponse: {
      /** @description Общее количество элементов */
      count?: number;
      /** @description URL следующей страницы */
      next?: string | null;
      /** @description URL предыдущей страницы */
      previous?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
