/**
 * Mock данные для товаров (Story 12.7)
 * Используются для development и тестирования
 *
 * TODO: Заменить на API calls в production
 */

import type { Product } from '@/types/api';
import { categoryPlaceholder } from '@/utils/placeholders';

export const MOCK_HIT_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Футбольный мяч Nike Premier League',
    slug: 'nike-premier-league-ball',
    brand: { id: 1, name: 'Nike', slug: 'nike', is_featured: false },
    retail_price: 4999,
    opt1_price: 4499,
    opt2_price: 4299,
    opt3_price: 3999,
    old_price: 6999,
    image: categoryPlaceholder('Nike Ball'),
    images: [],
    rating: 4.8,
    reviews_count: 124,
    is_hit: true,
    is_new: false,
    is_in_stock: true,
    stock_quantity: 50,
    description: 'Официальный мяч Premier League',
    short_description: 'Футбольный мяч профессионального уровня',
    category_id: 1,
    category: { id: 1, name: 'Футбол', slug: 'football' },
    is_sale: false,
    is_promo: false,
    is_premium: false,
    discount_percent: null,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 2,
    name: 'Кроссовки Adidas Ultraboost',
    slug: 'adidas-ultraboost',
    brand: { id: 2, name: 'Adidas', slug: 'adidas', is_featured: false },
    retail_price: 12999,
    opt1_price: 11999,
    opt2_price: 11499,
    opt3_price: 10999,
    old_price: 15999,
    image: categoryPlaceholder('Ultraboost'),
    images: [],
    rating: 4.9,
    reviews_count: 89,
    is_hit: true,
    is_new: false,
    is_in_stock: true,
    stock_quantity: 30,
    description: 'Кроссовки для бега с технологией Boost',
    short_description: 'Премиальные беговые кроссовки',
    category_id: 2,
    category: { id: 2, name: 'Бег', slug: 'running' },
    is_sale: false,
    is_promo: false,
    is_premium: false,
    discount_percent: null,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 3,
    name: 'Гантели Reebok 10 кг',
    slug: 'reebok-dumbbells-10kg',
    brand: { id: 3, name: 'Reebok', slug: 'reebok', is_featured: false },
    retail_price: 2999,
    opt1_price: 2699,
    opt2_price: 2499,
    opt3_price: 2299,
    image: categoryPlaceholder('Гантели'),
    images: [],
    rating: 4.7,
    reviews_count: 56,
    is_hit: true,
    is_new: false,
    is_in_stock: true,
    stock_quantity: 100,
    description: 'Гантели с неопреновым покрытием',
    short_description: 'Для домашних тренировок',
    category_id: 2,
    category: { id: 2, name: 'Фитнес', slug: 'fitness' },
    is_sale: false,
    is_promo: false,
    is_premium: false,
    discount_percent: null,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 4,
    name: 'Форма Nike Dri-FIT',
    slug: 'nike-dri-fit-kit',
    brand: { id: 1, name: 'Nike', slug: 'nike', is_featured: false },
    retail_price: 5999,
    opt1_price: 5499,
    opt2_price: 5199,
    opt3_price: 4799,
    old_price: 7999,
    image: categoryPlaceholder('Nike Kit'),
    images: [],
    rating: 4.6,
    reviews_count: 78,
    is_hit: true,
    is_new: false,
    is_in_stock: true,
    stock_quantity: 60,
    description: 'Футбольная форма с технологией Dri-FIT',
    short_description: 'Игровая форма',
    category_id: 1,
    category: { id: 1, name: 'Футбол', slug: 'football' },
    is_sale: false,
    is_promo: false,
    is_premium: false,
    discount_percent: null,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 5,
    name: 'Мат для йоги Adidas',
    slug: 'adidas-yoga-mat',
    brand: { id: 2, name: 'Adidas', slug: 'adidas', is_featured: false },
    retail_price: 1999,
    opt1_price: 1799,
    opt2_price: 1699,
    opt3_price: 1599,
    image: categoryPlaceholder('Yoga Mat'),
    images: [],
    rating: 4.5,
    reviews_count: 45,
    is_hit: true,
    is_new: false,
    is_in_stock: true,
    stock_quantity: 80,
    description: 'Нескользящий мат для йоги',
    short_description: 'Для фитнеса и йоги',
    category_id: 2,
    category: { id: 2, name: 'Йога', slug: 'yoga' },
    is_sale: false,
    is_promo: false,
    is_premium: false,
    discount_percent: null,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: 6,
    name: 'Велосипед детский 16"',
    slug: 'kids-bike-16',
    brand: { id: 4, name: 'Stels', slug: 'stels', is_featured: false },
    retail_price: 8999,
    opt1_price: 8199,
    opt2_price: 7799,
    opt3_price: 7299,
    image: categoryPlaceholder('Kids Bike'),
    images: [],
    rating: 4.8,
    reviews_count: 92,
    is_hit: true,
    is_new: false,
    is_in_stock: true,
    stock_quantity: 25,
    description: 'Детский велосипед с дополнительными колесами',
    short_description: 'Для детей 4-6 лет',
    category_id: 5,
    category: { id: 5, name: 'Велоспорт', slug: 'cycling' },
    is_sale: false,
    is_promo: false,
    is_premium: false,
    discount_percent: null,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
];

export const MOCK_NEW_PRODUCTS: Product[] = [
  {
    id: 11,
    name: 'Беговая дорожка HouseFit',
    slug: 'housefit-treadmill',
    brand: { id: 5, name: 'HouseFit', slug: 'housefit', is_featured: false },
    retail_price: 45999,
    opt1_price: 42999,
    opt2_price: 41499,
    opt3_price: 39999,
    image: categoryPlaceholder('Treadmill'),
    images: [],
    rating: 4.7,
    reviews_count: 12,
    is_hit: false,
    is_new: true,
    is_in_stock: true,
    stock_quantity: 10,
    description: 'Электрическая беговая дорожка для дома',
    short_description: 'Современная беговая дорожка',
    category_id: 2,
    category: { id: 2, name: 'Фитнес', slug: 'fitness' },
    is_sale: false,
    is_promo: false,
    is_premium: false,
    discount_percent: null,
    created_at: '2025-11-01',
    updated_at: '2025-11-01',
  },
  {
    id: 12,
    name: 'Боксерские перчатки Everlast 12 oz',
    slug: 'everlast-boxing-gloves-12oz',
    brand: { id: 6, name: 'Everlast', slug: 'everlast', is_featured: false },
    retail_price: 3999,
    opt1_price: 3599,
    opt2_price: 3399,
    opt3_price: 3199,
    image: categoryPlaceholder('Gloves'),
    images: [],
    rating: 4.8,
    reviews_count: 8,
    is_hit: false,
    is_new: true,
    is_in_stock: true,
    stock_quantity: 40,
    description: 'Профессиональные боксерские перчатки',
    short_description: 'Для тренировок и спаррингов',
    category_id: 3,
    category: { id: 3, name: 'Единоборства', slug: 'martial-arts' },
    is_sale: false,
    is_promo: false,
    is_premium: false,
    discount_percent: null,
    created_at: '2025-11-05',
    updated_at: '2025-11-05',
  },
  {
    id: 13,
    name: 'Плавки Arena Carbon Pro',
    slug: 'arena-carbon-pro-jammer',
    brand: { id: 7, name: 'Arena', slug: 'arena', is_featured: false },
    retail_price: 6999,
    opt1_price: 6299,
    opt2_price: 5999,
    opt3_price: 5699,
    image: categoryPlaceholder('Swimwear'),
    images: [],
    rating: 4.9,
    reviews_count: 5,
    is_hit: false,
    is_new: true,
    is_in_stock: true,
    stock_quantity: 20,
    description: 'Технологичные плавки для соревнований',
    short_description: 'Профессиональные плавки',
    category_id: 4,
    category: { id: 4, name: 'Плавание', slug: 'swimming' },
    is_sale: false,
    is_promo: false,
    is_premium: false,
    discount_percent: null,
    created_at: '2025-11-10',
    updated_at: '2025-11-10',
  },
  {
    id: 14,
    name: 'Самокат Razor A5 Lux',
    slug: 'razor-a5-lux-scooter',
    brand: { id: 8, name: 'Razor', slug: 'razor', is_featured: false },
    retail_price: 7999,
    opt1_price: 7199,
    opt2_price: 6899,
    opt3_price: 6499,
    image: categoryPlaceholder('Scooter'),
    images: [],
    rating: 4.6,
    reviews_count: 15,
    is_hit: false,
    is_new: true,
    is_in_stock: true,
    stock_quantity: 35,
    description: 'Складной самокат с большими колесами',
    short_description: 'Для детей и подростков',
    category_id: 5,
    category: { id: 5, name: 'Самокаты', slug: 'scooters' },
    is_sale: false,
    is_promo: false,
    is_premium: false,
    discount_percent: null,
    created_at: '2025-11-12',
    updated_at: '2025-11-12',
  },
  {
    id: 15,
    name: 'Штанга олимпийская 20 кг',
    slug: 'olympic-barbell-20kg',
    brand: { id: 9, name: 'Eleiko', slug: 'eleiko', is_featured: false },
    retail_price: 24999,
    opt1_price: 22999,
    opt2_price: 21999,
    opt3_price: 20999,
    image: categoryPlaceholder('Barbell'),
    images: [],
    rating: 5.0,
    reviews_count: 3,
    is_hit: false,
    is_new: true,
    is_in_stock: true,
    stock_quantity: 8,
    description: 'Профессиональная олимпийская штанга',
    short_description: 'Для пауэрлифтинга',
    category_id: 2,
    category: { id: 2, name: 'Тяжелая атлетика', slug: 'weightlifting' },
    is_sale: false,
    is_promo: false,
    is_premium: false,
    discount_percent: null,
    created_at: '2025-11-15',
    updated_at: '2025-11-15',
  },
  {
    id: 16,
    name: 'Кимоно для дзюдо Mizuno',
    slug: 'mizuno-judo-gi',
    brand: { id: 10, name: 'Mizuno', slug: 'mizuno', is_featured: false },
    retail_price: 8999,
    opt1_price: 8199,
    opt2_price: 7799,
    opt3_price: 7299,
    image: categoryPlaceholder('Kimono'),
    images: [],
    rating: 4.7,
    reviews_count: 6,
    is_hit: false,
    is_new: true,
    is_in_stock: true,
    stock_quantity: 15,
    description: 'Сертифицированное кимоно IJF для дзюдо',
    short_description: 'Для соревнований',
    category_id: 3,
    category: { id: 3, name: 'Дзюдо', slug: 'judo' },
    is_sale: false,
    is_promo: false,
    is_premium: false,
    discount_percent: null,
    created_at: '2025-11-18',
    updated_at: '2025-11-18',
  },
];
