# Generated by Django 5.2.7 on 2025-11-05 08:13

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0013_add_celery_task_id_to_import_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationImportSession",
            fields=[],
            options={
                "verbose_name": "Сессия импорта",
                "verbose_name_plural": "Сессии импорта",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("products.importsession",),
        ),
    ]
