# Generated by Django 5.2.7 on 2025-11-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
        ("products", "0013_add_celery_task_id_to_import_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportFrom1C",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "🚀 Импорт из 1С",
                "verbose_name_plural": "🚀 Импорт из 1С",
                "permissions": [("can_import_from_1c", "Может запускать импорт из 1С")],
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.DeleteModel(
            name="IntegrationImportSession",
        ),
        migrations.CreateModel(
            name="Session",
            fields=[],
            options={
                "verbose_name": "Сессия импорта",
                "verbose_name_plural": "Сессии импорта",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("products.importsession",),
        ),
    ]
