# Generated by Django 5.2.7 on 2025-11-05 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_importfrom1c_delete_integrationimportsession_session"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImportFrom1C",
        ),
    ]
