# Generated by Django 5.2.7 on 2026-01-22 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0003_delete_importfrom1c"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={
                "permissions": [("can_exchange_1c", "Can exchange with 1C")],
                "verbose_name": "Сессия импорта",
                "verbose_name_plural": "Сессии импорта",
            },
        ),
    ]
