# Generated by Django 4.2.16 on 2025-08-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_remove_brand_brands_unique_active_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Технические характеристики"
            ),
        ),
    ]
