# Generated by Django 4.2.16 on 2025-09-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_brand_slug_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
        ),
        migrations.AddField(
            model_name="product",
            name="last_sync_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последняя синхронизация"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает синхронизации"),
                    ("syncing", "Синхронизируется"),
                    ("synced", "Синхронизирован"),
                    ("error", "Ошибка синхронизации"),
                    ("conflict", "Конфликт данных"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус синхронизации",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="onec_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="ID в 1С",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["onec_id"], name="products_onec_id_c8f5de_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["sync_status"], name="products_sync_st_02c9fd_idx"
            ),
        ),
    ]
