# Generated by Django 4.2.16 on 2025-09-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_add_1c_integration_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="reserved_quantity",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Количество товара, зарезервированного в корзинах и заказах",
                verbose_name="Зарезервированное количество",
            ),
        ),
    ]
