# Generated by Django 5.2.7 on 2025-10-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_add_import_session_and_price_type"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="importsession",
            new_name="import_sess_import__f1fb4c_idx",
            old_name="import_sess_import__2f8c7d_idx",
        ),
        migrations.RenameIndex(
            model_name="importsession",
            new_name="import_sess_started_1783ac_idx",
            old_name="import_sess_started_9a3b5e_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_parent__07f0c8_idx",
            old_name="products_parent__6fa29e_idx",
        ),
        migrations.AddField(
            model_name="brand",
            name="onec_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Уникальный идентификатор бренда из 1С",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="ID в 1С",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="onec_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Уникальный идентификатор категории из 1С",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="ID в 1С",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="onec_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Составной ID из offers.xml: parent_id#sku_id",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="ID товара в 1С (SKU)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Доступное количество на складе",
                verbose_name="Количество на складе",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает синхронизации"),
                    ("in_progress", "Синхронизация"),
                    ("completed", "Синхронизировано"),
                    ("failed", "Ошибка"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Статус синхронизации",
            ),
        ),
    ]
