# Generated by Django 5.2.7 on 2025-11-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0012_rename_import_sess_import__2f8c7d_idx_import_sess_import__f1fb4c_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="importsession",
            name="celery_task_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="UUID задачи Celery для отслеживания прогресса",
                max_length=255,
                null=True,
                verbose_name="ID задачи Celery",
            ),
        ),
    ]
