# Generated by Django 5.2.7 on 2025-11-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_add_celery_task_id_to_import_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название бренда"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(max_length=255, verbose_name="Slug"),
        ),
    ]
