# Generated by Django 5.2.7 on 2025-11-16 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_remove_brand_name_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Процент скидки для отображения на бейдже (0-100)",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Процент скидки",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_hit",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Отображать бейдж 'Хит продаж' на карточке товара",
                verbose_name="Хит продаж",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Отображать бейдж 'Новинка' на карточке товара",
                verbose_name="Новинка",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_premium",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Премиум товар (эксклюзив, лимитированная серия)",
                verbose_name="Премиум",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_promo",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Товар участвует в акции/промо",
                verbose_name="Акция",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_sale",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Товар участвует в распродаже",
                verbose_name="Распродажа",
            ),
        ),
    ]
