# Generated by Django 5.2.7 on 2025-11-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_product_discount_percent_product_is_hit_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_hit", "is_active"], name="products_is_hit_09f1ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_new", "is_active"], name="products_is_new_eded74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_sale", "is_active"], name="products_is_sale_49e9eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_promo", "is_active"], name="products_is_prom_fe330c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_premium", "is_active"], name="products_is_prem_431475_idx"
            ),
        ),
    ]
