# Generated by Django 5.2.7 on 2025-11-24 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_product_products_is_hit_09f1ec_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="normalized_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Нормализованное название для дедупликации брендов",
                max_length=100,
                null=True,
                verbose_name="Нормализованное название",
            ),
        ),
        migrations.CreateModel(
            name="Brand1CMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "onec_id",
                    models.CharField(
                        db_index=True,
                        help_text="Уникальный идентификатор бренда из 1С",
                        max_length=100,
                        unique=True,
                        verbose_name="ID в 1С",
                    ),
                ),
                (
                    "onec_name",
                    models.CharField(
                        help_text="Оригинальное название бренда из 1С",
                        max_length=100,
                        verbose_name="Название в 1С",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        help_text="Master-бренд в системе",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onec_mappings",
                        to="products.brand",
                        verbose_name="Бренд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Маппинг бренда 1С",
                "verbose_name_plural": "Маппинги брендов 1С",
                "db_table": "products_brand_1c_mapping",
            },
        ),
    ]
