# Generated by Django 5.2.7 on 2025-11-24 14:30

from __future__ import annotations

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def populate_normalized_name(apps, schema_editor):
    """
    Заполняет поле normalized_name для всех существующих брендов.
    Разрешает коллизии путем добавления суффикса к дубликатам.
    """
    Brand = apps.get_model("products", "Brand")

    # Импортируем функцию нормализации
    from apps.products.utils.brands import normalize_brand_name

    collision_count = 0
    processed_count = 0
    normalized_names_used = set()

    for brand in Brand.objects.all():
        processed_count += 1

        # Вычисляем normalized_name
        if not brand.name:
            brand.normalized_name = None
            brand.save(update_fields=["normalized_name"])
            continue

        normalized = normalize_brand_name(brand.name)

        # Проверяем на коллизии
        if normalized in normalized_names_used:
            collision_count += 1
            # Добавляем суффикс для уникальности
            unique_normalized = f"{normalized}_brand_{brand.id}"
            logger.warning(
                f"Коллизия normalized_name: '{normalized}' для бренда '{brand.name}' (ID: {brand.id}). "
                f"Используется: '{unique_normalized}'"
            )
            brand.normalized_name = unique_normalized
        else:
            brand.normalized_name = normalized

        normalized_names_used.add(brand.normalized_name)
        brand.save(update_fields=["normalized_name"])

    logger.info(
        f"Заполнение normalized_name завершено. "
        f"Обработано брендов: {processed_count}, коллизий: {collision_count}"
    )


def reverse_populate_normalized_name(apps, schema_editor):
    """
    Откат миграции - очищает поле normalized_name.
    """
    Brand = apps.get_model("products", "Brand")
    Brand.objects.all().update(normalized_name=None)


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_add_normalized_name_to_brand"),
    ]

    operations = [
        migrations.RunPython(
            populate_normalized_name,
            reverse_populate_normalized_name,
        ),
    ]
