# Generated by Django 5.2.7 on 2025-11-24 14:31

from __future__ import annotations

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def migrate_onec_id_to_mapping(apps, schema_editor):
    """
    Переносит существующие Brand.onec_id в таблицу Brand1CMapping.
    """
    Brand = apps.get_model("products", "Brand")
    Brand1CMapping = apps.get_model("products", "Brand1CMapping")

    migrated_count = 0
    skipped_count = 0

    for brand in Brand.objects.filter(onec_id__isnull=False).exclude(onec_id=""):
        # Проверяем, не существует ли уже маппинг
        if Brand1CMapping.objects.filter(onec_id=brand.onec_id).exists():
            logger.warning(
                f"Маппинг для onec_id={brand.onec_id} уже существует, пропускаем бренд ID={brand.id}"
            )
            skipped_count += 1
            continue

        # Создаем маппинг
        Brand1CMapping.objects.create(
            brand=brand,
            onec_id=brand.onec_id,
            onec_name=brand.name,
        )
        migrated_count += 1

    logger.info(
        f"Миграция onec_id завершена. "
        f"Создано маппингов: {migrated_count}, пропущено: {skipped_count}"
    )


def reverse_migrate_onec_id_to_mapping(apps, schema_editor):
    """
    Откат миграции - удаляет все маппинги.
    """
    Brand1CMapping = apps.get_model("products", "Brand1CMapping")
    count = Brand1CMapping.objects.count()
    Brand1CMapping.objects.all().delete()
    logger.info(f"Удалено {count} маппингов при откате миграции")


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0018_populate_normalized_name"),
    ]

    operations = [
        migrations.RunPython(
            migrate_onec_id_to_mapping,
            reverse_migrate_onec_id_to_mapping,
        ),
    ]
