# Generated by Django 5.2.7 on 2025-11-24 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0019_migrate_onec_id_to_mapping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="onec_id",
        ),
    ]
