# Generated by Django 5.2.7 on 2025-11-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0020_remove_onec_id_from_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="normalized_name",
            field=models.CharField(
                db_index=True,
                help_text="Нормализованное название для дедупликации брендов",
                max_length=100,
                unique=True,
                verbose_name="Нормализованное название",
            ),
        ),
    ]
