# Generated by Django 5.2.7 on 2025-11-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0021_make_normalized_name_unique_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="onec_brand_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Исходный идентификатор бренда из CommerceML для обратной синхронизации",
                max_length=100,
                null=True,
                verbose_name="ID бренда в 1С",
            ),
        ),
    ]
