# Generated by Django 5.2.7 on 2025-12-04 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0025_load_basic_colors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название типа свойства (например, 'Цвет', 'Размер', 'Материал')",
                        max_length=255,
                        verbose_name="Название атрибута",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-совместимый идентификатор",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "onec_id",
                    models.CharField(
                        db_index=True,
                        help_text="Уникальный идентификатор атрибута из 1С",
                        max_length=255,
                        unique=True,
                        verbose_name="ID в 1С",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="Тип атрибута для будущей логики фильтрации",
                        max_length=50,
                        verbose_name="Тип атрибута",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Атрибут товара",
                "verbose_name_plural": "Атрибуты товаров",
                "db_table": "product_attributes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Конкретное значение атрибута (например, 'Красный', 'XL', 'Хлопок')",
                        max_length=255,
                        verbose_name="Значение",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-совместимый идентификатор",
                        max_length=255,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "onec_id",
                    models.CharField(
                        db_index=True,
                        help_text="Уникальный идентификатор значения атрибута из 1С",
                        max_length=255,
                        unique=True,
                        verbose_name="ID в 1С",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Значение атрибута",
                "verbose_name_plural": "Значения атрибутов",
                "db_table": "product_attribute_values",
                "ordering": ["attribute", "value"],
            },
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_sku_fe2039_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_stock_q_5d82ff_idx",
        ),
        migrations.RenameIndex(
            model_name="productvariant",
            new_name="product_var_product_b96575_idx",
            old_name="product_var_product_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="productvariant",
            new_name="product_var_sku_3a95f0_idx",
            old_name="product_var_sku_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="productvariant",
            new_name="product_var_onec_id_5d9811_idx",
            old_name="product_var_onec_id_g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="productvariant",
            new_name="product_var_color_n_f6070f_idx",
            old_name="product_var_color_n_j1k2l3_idx",
        ),
        migrations.RenameIndex(
            model_name="productvariant",
            new_name="product_var_size_va_67b764_idx",
            old_name="product_var_size_va_m4n5o6_idx",
        ),
        migrations.RenameIndex(
            model_name="productvariant",
            new_name="product_var_stock_q_ecefab_idx",
            old_name="product_var_stock_q_p7q8r9_idx",
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="attribute",
            field=models.ForeignKey(
                help_text="Тип атрибута, к которому относится это значение",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="products.attribute",
                verbose_name="Атрибут",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Атрибуты товара (цвет, материал, размер и т.д.)",
                related_name="products",
                to="products.attributevalue",
                verbose_name="Атрибуты",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="attributes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Атрибуты варианта товара (цвет, материал, размер и т.д.)",
                related_name="variants",
                to="products.attributevalue",
                verbose_name="Атрибуты",
            ),
        ),
        migrations.AddIndex(
            model_name="attributevalue",
            index=models.Index(
                fields=["attribute", "value"], name="product_att_attribu_d01970_idx"
            ),
        ),
    ]
