# Generated by Django 5.2.7 on 2025-12-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0026_attribute_attributevalue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importsession",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("catalog", "Каталог товаров"),
                    ("attributes", "Атрибуты (справочники)"),
                    ("images", "Изображения товаров"),
                    ("stocks", "Остатки товаров"),
                    ("prices", "Цены товаров"),
                    ("customers", "Клиенты"),
                ],
                default="catalog",
                max_length=20,
                verbose_name="Тип импорта",
            ),
        ),
    ]
