# Generated by Django 5.2.7 on 2025-12-04 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0027_alter_importsession_import_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Атрибут активен и отображается в каталоге",
                verbose_name="Активный атрибут",
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="normalized_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Нормализованное название для дедупликации атрибутов",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Нормализованное название",
            ),
        ),
        migrations.CreateModel(
            name="Attribute1CMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "onec_id",
                    models.CharField(
                        db_index=True,
                        help_text="Уникальный идентификатор атрибута из 1С",
                        max_length=255,
                        unique=True,
                        verbose_name="ID в 1С",
                    ),
                ),
                (
                    "onec_name",
                    models.CharField(
                        help_text="Оригинальное название атрибута из 1С",
                        max_length=255,
                        verbose_name="Название в 1С",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("goods", "Goods"), ("offers", "Offers")],
                        help_text="Тип файла откуда импортирован атрибут (goods/offers)",
                        max_length=10,
                        verbose_name="Источник импорта",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        help_text="Master-атрибут в системе",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onec_mappings",
                        to="products.attribute",
                        verbose_name="Атрибут",
                    ),
                ),
            ],
            options={
                "verbose_name": "Маппинг атрибута 1С",
                "verbose_name_plural": "Маппинги атрибутов 1С",
                "db_table": "product_attribute_1c_mappings",
                "indexes": [
                    models.Index(
                        fields=["attribute", "source"],
                        name="product_att_attribu_e7d585_idx",
                    )
                ],
            },
        ),
    ]
