# Generated by Django 5.2.7 on 2025-12-04 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0030_finalize_attribute_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeValue1CMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "onec_id",
                    models.CharField(
                        db_index=True,
                        help_text="Уникальный идентификатор значения атрибута из 1С",
                        max_length=255,
                        unique=True,
                        verbose_name="ID в 1С",
                    ),
                ),
                (
                    "onec_value",
                    models.CharField(
                        help_text="Оригинальное значение атрибута из 1С",
                        max_length=255,
                        verbose_name="Значение в 1С",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("goods", "Goods"), ("offers", "Offers")],
                        help_text="Тип файла откуда импортировано значение (goods/offers)",
                        max_length=10,
                        verbose_name="Источник импорта",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Маппинг значения атрибута 1С",
                "verbose_name_plural": "Маппинги значений атрибутов 1С",
                "db_table": "product_attribute_value_1c_mappings",
            },
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="normalized_value",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Нормализованное значение для дедупликации",
                max_length=255,
                null=True,
                verbose_name="Нормализованное значение",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="normalized_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Нормализованное название для дедупликации атрибутов",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Нормализованное название",
            ),
        ),
        migrations.AddConstraint(
            model_name="attributevalue",
            constraint=models.UniqueConstraint(
                fields=("attribute", "normalized_value"),
                name="unique_attribute_normalized_value",
            ),
        ),
        migrations.AddField(
            model_name="attributevalue1cmapping",
            name="attribute_value",
            field=models.ForeignKey(
                help_text="Master-значение атрибута в системе",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onec_mappings",
                to="products.attributevalue",
                verbose_name="Значение атрибута",
            ),
        ),
        migrations.AddIndex(
            model_name="attributevalue1cmapping",
            index=models.Index(
                fields=["attribute_value", "source"],
                name="product_att_attribu_29affe_idx",
            ),
        ),
    ]
