# Generated by Django 5.2.7 on 2025-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0032_finalize_attribute_value_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributevalue",
            name="normalized_value",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Нормализованное значение для дедупликации",
                max_length=255,
                null=True,
                verbose_name="Нормализованное значение",
            ),
        ),
    ]
