# Generated by Django 5.2.7 on 2025-12-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0033_alter_attributevalue_normalized_value"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["retail_price"], name="product_var_retail__f0326a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "stock_quantity"], name="idx_variant_product_stock"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "retail_price"], name="idx_variant_product_price"
            ),
        ),
    ]
