# Generated by Django 5.2.7 on 2026-01-10 16:08

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0035_add_variants_import_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="msrp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Минимальная рекомендованная розничная цена (информационно)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="МРЦ",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="rrp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Рекомендованная розничная цена (информационно)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="РРЦ",
            ),
        ),
    ]
