# Generated by Django 5.2.7 on 2026-01-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0036_productvariant_msrp_productvariant_rrp"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="min_order_quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Минимальное количество товара для заказа (для B2B)",
                verbose_name="Минимальное количество заказа",
            ),
        ),
    ]
