# Generated by Django 5.2.7 on 2026-01-17 09:43

from django.db import migrations, models


def update_price_type_codes(apps, schema_editor):
    PriceType = apps.get_model("products", "PriceType")

    # Update recommended_retail_price -> rrp
    PriceType.objects.filter(product_field="recommended_retail_price").update(
        product_field="rrp"
    )

    # Update max_suggested_retail_price -> msrp
    PriceType.objects.filter(product_field="max_suggested_retail_price").update(
        product_field="msrp"
    )


def reverse_update_price_type_codes(apps, schema_editor):
    PriceType = apps.get_model("products", "PriceType")

    # Reverse rrp -> recommended_retail_price
    PriceType.objects.filter(product_field="rrp").update(
        product_field="recommended_retail_price"
    )

    # Reverse msrp -> max_suggested_retail_price
    PriceType.objects.filter(product_field="msrp").update(
        product_field="max_suggested_retail_price"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0037_product_min_order_quantity"),
    ]

    operations = [
        migrations.RunPython(
            update_price_type_codes, reverse_code=reverse_update_price_type_codes
        ),
        migrations.AlterField(
            model_name="pricetype",
            name="product_field",
            field=models.CharField(
                choices=[
                    ("retail_price", "Розничная цена"),
                    ("opt1_price", "Оптовая цена уровень 1"),
                    ("opt2_price", "Оптовая цена уровень 2"),
                    ("opt3_price", "Оптовая цена уровень 3"),
                    ("trainer_price", "Цена для тренера"),
                    ("federation_price", "Цена для представителя федерации"),
                    ("rrp", "Рекомендованная розничная цена"),
                    ("msrp", "Максимальная рекомендованная цена"),
                ],
                help_text="Поле Product, в которое мапится эта цена",
                max_length=50,
                verbose_name="Поле в модели Product",
            ),
        ),
    ]
