# Generated by Django 5.2.7 on 2026-01-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0038_update_pricetype_codes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importsession",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Сессия импорта",
                "verbose_name_plural": "Сессии импорта",
            },
        ),
        migrations.RemoveIndex(
            model_name="importsession",
            name="import_sess_started_1783ac_idx",
        ),
        migrations.AddField(
            model_name="importsession",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="importsession",
            name="report",
            field=models.TextField(
                blank=True,
                help_text="Текстовый лог/отчет о выполнении",
                verbose_name="Отчет",
            ),
        ),
        migrations.AddField(
            model_name="importsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="importsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В очереди"),
                    ("started", "Начато"),
                    ("in_progress", "В процессе"),
                    ("completed", "Завершено"),
                    ("failed", "Ошибка"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddIndex(
            model_name="importsession",
            index=models.Index(
                fields=["-created_at"], name="import_sess_created_800466_idx"
            ),
        ),
    ]
