# Generated by Django 5.2.7 on 2026-01-24 09:53

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0039_alter_importsession_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importsession",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 1, 24, 9, 53, 16, 66513, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
    ]
