# Generated by Django 5.2.7 on 2026-01-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0040_alter_importsession_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="importsession",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID сессии из URL (sessid) для отслеживания транзакции",
                max_length=40,
                null=True,
                verbose_name="Ключ сессии (SESSID)",
            ),
        ),
    ]
