# Generated by Django 5.2.7 on 2026-01-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0041_importsession_session_key"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="importsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "started", "in_progress"])
                ),
                fields=("session_key",),
                name="unique_active_session_key",
            ),
        ),
    ]
