# Generated by Django 5.2.7 on 2026-02-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0044_brand_slug_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.ImageField(blank=True, upload_to="brands/", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Активный"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Показывать на главной"),
        ),
    ]
