# Generated by Django 5.2.7 on 2026-02-18 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0045_brand_is_featured_is_active_db_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageCategory",
            fields=[],
            options={
                "verbose_name": "Категория для главной",
                "verbose_name_plural": "Категории для главной",
                "ordering": ["sort_order", "id"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("products.category",),
        ),
    ]
