# Generated by Django 5.2.7 on 2026-02-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0046_homepagecategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.FileField(blank=True, upload_to="categories/icons/", verbose_name="Иконка"),
        ),
    ]
