# Generated by Django 5.2.7 on 2026-08-02 07:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0051_alter_productvariant_vat_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="opt4_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Цена для роли wholesale_level4",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Оптовая цена уровень 4",
            ),
        ),
        migrations.AlterField(
            model_name="pricetype",
            name="product_field",
            field=models.CharField(
                choices=[
                    ("retail_price", "Розничная цена"),
                    ("opt1_price", "Оптовая цена уровень 1"),
                    ("opt2_price", "Оптовая цена уровень 2"),
                    ("opt3_price", "Оптовая цена уровень 3"),
                    ("opt4_price", "Оптовая цена уровень 4"),
                    ("trainer_price", "Цена для тренера"),
                    ("federation_price", "Цена для представителя федерации"),
                    ("rrp", "Рекомендованная розничная цена"),
                    ("msrp", "Максимальная рекомендованная цена"),
                ],
                help_text="Поле Product, в которое мапится эта цена",
                max_length=50,
                verbose_name="Поле в модели Product",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("opt4_price__gte", 0), ("opt4_price__isnull", True), _connector="OR"),
                name="products_opt4_price_positive",
            ),
        ),
    ]
