# Generated by Django 5.2.7 on 2026-09-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0054_price_type_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="article",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Артикул номенклатуры из goods.xml",
                max_length=100,
                verbose_name="Артикул",
            ),
        ),
    ]
